#  spring.mail.host=smtp.example.com
#    spring.mail.port=587
#    spring.mail.username=your-email@example.com
#    spring.mail.password=your-email-password
#    spring.mail.properties.mail.smtp.auth=true
#    spring.mail.properties.mail.smtp.starttls.enable=true

#Human Resource Management System and Payroll system
server:
  port: 8090
spring:
  devtools:
    restart:
      enabled: true
  application:
    name: Hrms
  mail:
    host: smtp.yourmaildomain.com
    port: 587
    username: yourmail@gmail.com
    password: yourappmailpassowrd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #Database connection
  datasource:
    url: jdbc:mysql://localhost:3306/hrms
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: admin
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
        filter: DEBUG
#  logging.level.org.springframework.security=DEBUG
#  logging.level.org.springframework.web.filter=DEBUG

